# Generated by Django 3.2.12 on 2022-03-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
