# Generated by Django 3.2.12 on 2022-03-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], default='seller', max_length=10),
            preserve_default=False,
        ),
    ]
