# Generated by Django 3.2.12 on 2022-03-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deposit',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (20, 20), (50, 50), (100, 100)], default=(0, 0)),
        ),
    ]
